baseURL = 'https://mirzayevio.github.io'
languageCode = 'en-us'
title = 'Farid`s personal space & blog'
theme = 'cactus'
copyright = "Farid Mirzayev"

[taxonomies]
category = 'categories'
tag = 'tags'

[params]
colortheme = "dark" # dark, light, white, or classic
mainSectionTitle = "Posts"
dateFormat = "Jan 2, 2006"
rss = true
css = ["css/custom.css"]
  

[[params.social]]
name = "linkedin"
link = "https://www.linkedin.com/in/mirzayevio/"

[[params.social]]
name = "email"
link = "mirzayevfarid@gmail.com"

[[params.social]]
name = "github"
link = "https://github.com/mirzayevio"

[[params.social]]
name = "rss"
link = "https://mirzayevio.github.io/index.xml"

# Main menu which appears below site header.
[[menu.main]]
name = "Posts"
url = "/posts"
weight = 3

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Bookmarks"
url = "/bookmarks"
weight = 4

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'nord'
tabWidth = 4





















